// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// Defines values for RegistryFormat.
const (
	RegistryFormatFile RegistryFormat = "file"
	RegistryFormatGo   RegistryFormat = "go"
	RegistryFormatNpm  RegistryFormat = "npm"
	RegistryFormatPypi RegistryFormat = "pypi"
)

// Valid indicates whether the value is a known member of the RegistryFormat enum.
func (e RegistryFormat) Valid() bool {
	switch e {
	case RegistryFormatFile:
		return true
	case RegistryFormatGo:
		return true
	case RegistryFormatNpm:
		return true
	case RegistryFormatPypi:
		return true
	default:
		return false
	}
}

// Defines values for RegistryInputFormat.
const (
	RegistryInputFormatFile RegistryInputFormat = "file"
	RegistryInputFormatGo   RegistryInputFormat = "go"
	RegistryInputFormatNpm  RegistryInputFormat = "npm"
	RegistryInputFormatPypi RegistryInputFormat = "pypi"
)

// Valid indicates whether the value is a known member of the RegistryInputFormat enum.
func (e RegistryInputFormat) Valid() bool {
	switch e {
	case RegistryInputFormatFile:
		return true
	case RegistryInputFormatGo:
		return true
	case RegistryInputFormatNpm:
		return true
	case RegistryInputFormatPypi:
		return true
	default:
		return false
	}
}

// Registry defines model for Registry.
type Registry struct {
	CreatedAt *time.Time      `json:"CreatedAt,omitempty"`
	DeletedAt *time.Time      `json:"DeletedAt,omitempty"`
	Format    *RegistryFormat `json:"Format,omitempty"`
	ID        *int            `json:"ID,omitempty"`
	Name      *string         `json:"Name,omitempty"`
	UpdatedAt *time.Time      `json:"UpdatedAt,omitempty"`
}

// RegistryFormat defines model for Registry.Format.
type RegistryFormat string

// RegistryInput defines model for RegistryInput.
type RegistryInput struct {
	Format *RegistryInputFormat `json:"Format,omitempty"`
	Name   string               `json:"Name"`
}

// RegistryInputFormat defines model for RegistryInput.Format.
type RegistryInputFormat string

// CreateRegistryJSONRequestBody defines body for CreateRegistry for application/json ContentType.
type CreateRegistryJSONRequestBody = RegistryInput

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListRegistries request
	ListRegistries(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateRegistryWithBody request with any body
	CreateRegistryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateRegistry(ctx context.Context, body CreateRegistryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListRegistries(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListRegistriesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRegistryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRegistryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRegistry(ctx context.Context, body CreateRegistryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRegistryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListRegistriesRequest generates requests for ListRegistries
func NewListRegistriesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/registries")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateRegistryRequest calls the generic CreateRegistry builder with application/json body
func NewCreateRegistryRequest(server string, body CreateRegistryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateRegistryRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateRegistryRequestWithBody generates requests for CreateRegistry with any type of body
func NewCreateRegistryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/registries")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListRegistriesWithResponse request
	ListRegistriesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListRegistriesResponse, error)

	// CreateRegistryWithBodyWithResponse request with any body
	CreateRegistryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRegistryResponse, error)

	CreateRegistryWithResponse(ctx context.Context, body CreateRegistryJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRegistryResponse, error)
}

type ListRegistriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Registry
}

// Status returns HTTPResponse.Status
func (r ListRegistriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListRegistriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListRegistriesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateRegistryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Registry
}

// Status returns HTTPResponse.Status
func (r CreateRegistryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateRegistryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateRegistryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListRegistriesWithResponse request returning *ListRegistriesResponse
func (c *ClientWithResponses) ListRegistriesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListRegistriesResponse, error) {
	rsp, err := c.ListRegistries(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListRegistriesResponse(rsp)
}

// CreateRegistryWithBodyWithResponse request with arbitrary body returning *CreateRegistryResponse
func (c *ClientWithResponses) CreateRegistryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRegistryResponse, error) {
	rsp, err := c.CreateRegistryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRegistryResponse(rsp)
}

func (c *ClientWithResponses) CreateRegistryWithResponse(ctx context.Context, body CreateRegistryJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRegistryResponse, error) {
	rsp, err := c.CreateRegistry(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRegistryResponse(rsp)
}

// ParseListRegistriesResponse parses an HTTP response from a ListRegistriesWithResponse call
func ParseListRegistriesResponse(rsp *http.Response) (*ListRegistriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListRegistriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Registry
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateRegistryResponse parses an HTTP response from a CreateRegistryWithResponse call
func ParseCreateRegistryResponse(rsp *http.Response) (*CreateRegistryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateRegistryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Registry
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}
